#!/bin/bash
#1.try/catch and stuff
#https://gist.github.com/YakDriver/d5285a1d6f0f7b595240f508665e856d

#npm -v

#2 ifs?


#npm i -g @angular/cli
#mv angularfolder/folder angularfolder/angfolderOld
#cd angularfolder
#ng new angularfoldertitle
#cd angularfoldertitle
#ng add @angular/material
#mv -r ../angfolderOld/* ./
